template: $CHANGES
name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
exclude-labels:
  - dependencies
  - skip-changelog
autolabeler:
  - label: bug
    branch:
      - "/fix\\/.+/"
  - label: change
    branch:
      - "/change\\/.+/"
  - label: enhancement
    branch:
      - "/feature\\/.+/"
      - "/feat\\/.+/"
      - "/improve\\/.+/"
  - label: ci
    files:
      - .github/**/*
  - label: breaking-change
    title:
      - "/.+!:.+/"
categories:
  - title: "💥 破坏性变更"
    labels:
      - breaking-change
  - title: "🚀 新功能"
    labels:
      - enhancement
  - title: "🐛 Bug 修复"
    labels:
      - bug
  - title: "💫 杂项"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
  patch:
    labels:
      - patch
  default: patch
